---
- hosts: all
  become: true
  tasks:
  - name: install apache2 package
    package:
      name: 
      - "{{ apache_package }}"
      - "{{ php_package }}"
      state: latest
      update_cache: yes 
  - name: install curl package
    apt:
      name: curl
      state: latest
  - name: restart apache2 process
    service: 
        name: apache2 
        state: restarted
