---
- hosts: all
  become: true
  pre_tasks:
  - name: update all packages
    package:
      state: latest
      update_cache: yes 
    when: ansible_distribution == "Ubuntu"

- hosts: test_servers
  become: true
  tasks:
  - name: install curl
    tags: "test"
    package:
      name: curl
      state: latest
      update_cache: yes 
    when: ansible_distribution == "Ubuntu"
   
- hosts: web_servers
  become: true
  tasks:
  - name: install apache2 package
    tags: "web,apache"
    package:
      name: 
      - "{{ apache_package }}"
      - "{{ php_package }}"
      state: latest
      update_cache: yes 
  - name: copy default html file
    tags: "web,apache"
    copy: 
        src: default_site.html 
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
    register: httpd
  - name: restart apache2 process
    service: 
        name: apache2 
        state: restarted
    when: httpd.changed
